In [61]:
from pymatgen.ext.matproj import MPRester
from pymatgen.io.cif import CifWriter

with MPRester("5TRoGi3ks3zfqgmPsey1") as m:
    structure = m.get_structure_by_material_id("mp-754883")
    w = CifWriter(structure)
    w.write_file('mystructure.cif')

In [62]:
from pymatgen.core.operations import SymmOp
import numpy as np
from IPython.display import Markdown, display
def printmd(string):
    display(Markdown(string))

In [63]:
printmd('**Première opération de symétrie: rotation d ordre 3**')

**Première opération de symétrie: rotation d ordre 3**

Correspond au 3ème élément de symétrie dans le CIF. Cette opération envoie un atome situé en (x,y,z) vers une position (-y,x-y,z) par une rotation autour de l'axe c. Cette opération peut être représentée par une matrice de rotation qui sera appliquée sur le vecteur position initiale de l'atome (x,y,z).

In [64]:
print('La matrice de rotation associée à cette opération est:')
op1 = SymmOp.from_xyz_string('-y, x-y, z')
print(op1.rotation_matrix)

La matrice de rotation associée à cette opération est:
[[ 0. -1.  0.]
 [ 1. -1.  0.]
 [ 0.  0.  1.]]


La relation finale est alors obtenue:

![](C3m.PNG)

In [65]:
print('Rotation C3 pour un atome de potassium dont la position initiale (x, y, z) est donnée par (2/3, 1/3, 1/3):')
print(op1.operate((2/3,1/3,1/3)))

Rotation C3 pour un atome de potassium dont la position initiale (x, y, z) est donnée par (2/3, 1/3, 1/3):
[-0.33333333  0.33333333  0.33333333]


L'image ci-dessous montre l'effet de cette rotation sur l'atome potassium. On voit bien que celui-ci effectue une rotation autour de l'axe c, qui est l'axe de base de la maille conventionnelle. Cet axe de rotation C3 dans la direction [001] est bien représenté sur l'image par une flèche rouge.

![](rot.PNG)

In [66]:
printmd('**Deuxième opération de symétrie: réflexion d un atome par rapport à un plan miroir**')

**Deuxième opération de symétrie: réflexion d un atome par rapport à un plan miroir**

Correspond à l'élément de symétrie numéro 8 dans le CIF. Cette opération envoie un atome situé en (x,y,z) vers une position (-y,-x,z) par l'application d'un plan miroir m passant par l'origine. Cette opération peut être représentée par une matrice de rotation qui sera appliquée sur le vecteur position initiale de l'atome (x,y,z).

In [67]:
print('La matrice de rotation associée à cette opération est:')
op2 = SymmOp.from_xyz_string('-y, -x, z')
print(op2.rotation_matrix)

La matrice de rotation associée à cette opération est:
[[ 0. -1.  0.]
 [-1.  0.  0.]
 [ 0.  0.  1.]]


La relation finale est alors obtenue:

![](pm.PNG)

In [68]:
print('Application du plan miroir m à un atome d holmium dont la position initiale (x, y, z) est donnée par (2/3, 1/3, 0.83):')
print(op2.operate((2/3,1/3,0.83)))

Application du plan miroir m à un atome d holmium dont la position initiale (x, y, z) est donnée par (2/3, 1/3, 0.83):
[-0.33333333 -0.66666667  0.83      ]


L'image ci-dessous montre l'effet du plan miroir sur l'atome d'holmium. On voit bien la symétrie entre l'atome initial et son image, imposée par le plan miroir (représenté en vert).

![](P.PNG)


In [69]:
printmd('**Troisième opération de symétrie: translation d un atome**')

**Troisième opération de symétrie: translation d un atome**

Correspond à l'élément de symétrie numéro 13 dans le CIF. Cette opération envoie un atome situé en (x,y,z) vers une position (x-1/3,y+1/3,z+1/3) par une translation de l'atome concerné. Cette opération peut être représentée par la combinaison d'une matrice de rotation qui sera appliquée sur le vecteur position initiale de l'atome (x,y,z) et d'un vecteur de translation.

In [70]:
print('La matrice de rotation associée à cette opération est:')
op3 = SymmOp.from_xyz_string('x-1/3, y+1/3, z+1/3')
print(op3.rotation_matrix)
print(' ')
print('Le vecteur de translation associé à cette opération est:')
print(op3.translation_vector)

La matrice de rotation associée à cette opération est:
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
 
Le vecteur de translation associé à cette opération est:
[-0.33333333  0.33333333  0.33333333]


La relation finale est alors obtenue:

![](Trm.PNG)


In [71]:
print('Application de l opération de translation à un atome d oxygène dont la position initiale (x, y, z) est donnée par (2/3, 1/3, 0.56):')
print(op3.operate((2/3,1/3,0.56)))

Application de l opération de translation à un atome d oxygène dont la position initiale (x, y, z) est donnée par (2/3, 1/3, 0.56):
[0.33333333 0.66666667 0.89333333]


L'image ci-dessous montre l'effet la translation sur l'atome d'oxygène. L'application de l'opération translation est illustrée par la flèche jaune. On remarque bien que sa position a changé selon les trois axes de base de la maille conventionnelle. 

![](Tr.PNG)